### ISSUE TITLE
System Status Filesystem Usage script error

### ISSUE THREAD

**Issue by ScaredyCat** [deeztek/Hermes-Secure-Email-Gateway#30]
Logging into the admin interface I am presented with the following warning box. 
![error](https://user-images.githubusercontent.com/168872/182125078-6e0d4d37-ca7a-4311-b1d9-0d22ec8bc4b6.png)

Examining the script, it contains:

`#!/bin/bash
df -hl | awk '/^\/dev\/mapper/ubuntu--vg-ubuntu--lv/ { sum+=$5 } END { print sum }'
`
Executing script:

`awk: cmd. line:1: /^\/dev\/mapper/ubuntu--vg-ubuntu--lv/ { sum+=$5 } END { print sum }
awk: cmd. line:1:                                        ^ syntax error
`
It also looks like a new script is generated on each page load/refresh, is this expected behaviour?

**Comment by deeztek** [comment]
Hi, a new script generated on each page load/refresh is expected behavior. The error is caused by the script not being able to handle LVM devices which unfortunately is the default behavior for Ubuntu during drive setup.

**Comment by deeztek** [comment]
Issued a patch to fix this issue. Please download the script below and run it as root in your system to update the file in question and it should resolve the issue:

[https://raw.githubusercontent.com/deeztek/Hermes-Secure-Email-Gateway/master/patches/c93730b_issue_30.sh](https://raw.githubusercontent.com/deeztek/Hermes-Secure-Email-Gateway/master/patches/c93730b_issue_30.sh)

**Comment by ScaredyCat** [comment]
The patch creates a  

`get_system_root_filesystem_usage.cfm.1
`
file due to the existing version. Moving the old file to a backup folder and renaming  the .1 the error is still generated, the generated code is still the same (trailing slash) . Is there somehting else that needs to be done after the file is installed? I've restarted . Is the .cfm data cached somewhere?

**Comment by deeztek** [comment]
Fixed the script to delete the existing file and replace it with the new version. Can you try to run the new patch script:

https://raw.githubusercontent.com/deeztek/Hermes-Secure-Email-Gateway/master/patches/c93730b_issue_30.sh

If you still get the same error, can you share the output of the following command:

`df -h`

Thanks

**Comment by deeztek** [comment]
closing issue as fixed. Please re-open if any more problems.
